### ISSUE TITLE
Raw CAN logs

### ISSUE THREAD

**Issue by superwofy** [joeroback/racechrono-canbus#3]
Hello Joe,

Is there any chance you could attach any raw CAN logs you may have collected while developing this?
I am working on implementing the CRC on acceleration messages 0x199, 0x19A...

Thank you.

**Comment by joeroback** [comment]
unfortunately i do not have any CAN logs collected while in motion. i probably do have a RaceChrono session with those values, it should have acceleration messages from iPhone, Racebox Mini, and CAN, so you should be able to even compare them. i'll have to look this weekend for them, as they would be on a spare phone i only use for the track that i do not have with me at the moment

i guess they would be calculated values, tho, not the raw CAN values, but you could reverse calculate that if needed. they would be `bytesToUIntLe(raw, 2, 2) * 0.002 - 65` in terms of [RaceChrono equations](https://racechrono.com/support/equations).

**Comment by joeroback** [comment]
[session_20230718_120003_hpr_full_lap4_v3.csv](https://github.com/joeroback/racechrono-canbus/files/13196087/session_20230718_120003_hpr_full_lap4_v3.csv)

**Comment by superwofy** [comment]
Thank you!
