### ISSUE TITLE
Transmitting messages

### ISSUE THREAD

**Issue by dn00** [joeroback/racechrono-canbus#5]
Hey this is some beautiful code. This is my first Arduino project so please bare with me. I'm trying to set up the controller so that it would be able to transmit messages as well. The issue is that the RX interrupt is never triggered after I load a frame and transmit with `twai_ll_set_cmd_self_rx_request()`. Here are the changes I've made:

1. Set mode to `TWAI_MODE_NO_ACK`. I currently only have one board to play around with so I can't connect another node yet.
2. Set the TX pin
```c
    gpio_set_pull_mode(CAN_TX_PIN, GPIO_FLOATING);
    esp_rom_gpio_connect_out_signal(CAN_TX_PIN, TWAI_TX_IDX, false, false);
    esp_rom_gpio_pad_select_gpio(CAN_TX_PIN);
    gpio_set_direction(CAN_TX_PIN, GPIO_MODE_OUTPUT);
```
3. In my send method, I load a message frame with `twai_ll_set_tx_buffer(dev, &tx_buffer)` then call `twai_ll_set_cmd_tx(dev)` or `twai_ll_set_cmd_self_rx_request(dev)` but neither triggers the RX interrupt.

`twai_ll_is_last_tx_successful()` return false and `twai_ll_get_status()` returns 0x00000030.

What am I missing? My goal is to take a 0-5v input from an ethanol analyzer and send a zeitronix formatted message to bootmod3. Any help is appreciated.

**Comment by dn00** [comment]
I fixed by setting GPIO differently

```c
        gpio_config_t gpio_conf;
        gpio_conf.mode = GPIO_MODE_OUTPUT;
        gpio_conf.intr_type = GPIO_INTR_DISABLE;
        gpio_conf.pull_down_en = GPIO_PULLDOWN_DISABLE;
        gpio_conf.pull_up_en = GPIO_PULLUP_DISABLE;
        gpio_conf.pin_bit_mask = 1ULL << CAN_TX_PIN;
        gpio_config(&gpio_conf);
        esp_rom_gpio_connect_out_signal(CAN_TX_PIN, TWAI_TX_IDX, false, false);
```

**Comment by joeroback** [comment]
yea, i specifically didn't enable any transmit stuff, as my use-case is read-only, but it seems like you figured it out. i basically did not enable any of the TX interrupts, but the IDF twai API has good examples of doing this as well

**Comment by dn00** [comment]
This is my first Arduino project so I'm kind of skipping a lot of steps beginners would want to go through before attempting something this complex 😅. However, your code is clean and organized which helps a lot. Really appreciate you sharing it.

**Comment by joeroback** [comment]
one thing you might look at, i am explicitly putting the CAN transceiver in listen-only mode
`twai_ll_set_mode(dev, TWAI_MODE_LISTEN_ONLY);    // freeze REC by changing to LOM mode`

you might consider changing that to normal mode: `TWAI_MODE_NORMAL`
https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32/api-reference/peripherals/twai.html#enumerations

if you are planning on sending messages on the CAN bus

**Comment by dn00** [comment]
Yep I currently have it set to NO_ACK for self tests. There's a few things I need to implement before I'll test it on the car.
